In [7]:
import utils.utils as utils
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
insampleRet = pd.read_csv("data/etf_returns_insample.csv", index_col=0, parse_dates=True)
outsampleRet = pd.read_csv("data/etf_returns_outsample.csv", index_col=0, parse_dates=True)
prices = pd.read_csv("data/etf_prices.csv", index_col=0, parse_dates=True)

In [9]:
insampleRet

,EFA,GLD,HYG,IWM,LQD,QQQ,SPY,TLT
Date,,,,,,,,
2007-04-12,0.006655,-0.001343,0.000671,0.006702,0.001503,0.007886,0.004434,0.000228
2007-04-13,0.003311,0.012609,-0.001821,0.006412,-0.001692,0.002018,0.004552,-0.003094
2007-04-16,0.010497,0.008221,-0.000384,0.013673,0.000847,0.009140,0.009451,0.005495
2007-04-17,0.000126,-0.005865,-0.000480,-0.003036,0.005436,0.002217,0.002655,0.005578
2007-04-18,-0.000377,0.005573,0.000289,-0.005854,0.000282,-0.003327,0.001222,0.004982
...,...,...,...,...,...,...,...,...
2018-12-24,-0.011708,0.010891,-0.007506,-0.019588,-0.002317,-0.025110,-0.026778,0.004958
2018-12-26,0.022938,-0.003004,0.016687,0.046943,-0.000803,0.060567,0.049290,-0.010774
2018-12-27,0.002916,0.007576,-0.000617,0.004160,0.000000,0.003862,0.007648,0.000166
2018-12-28,0.005296,0.004056,0.001482,0.002864,0.004722,-0.000523,-0.001291,0.008379
2018-12-31,0.001532,0.001568,0.000740,0.007797,0.002751,0.008398,0.008721,0.003793

In [16]:
outsampleRet

,EFA,GLD,HYG,IWM,LQD,QQQ,SPY,TLT
Date,,,,,,,,
2019-01-02,-0.002044,0.000660,-0.001357,0.005660,0.003098,0.004011,0.001040,0.005254
2019-01-03,-0.009076,0.009025,0.000494,-0.018059,0.000442,-0.033217,-0.024152,0.011315
2019-01-04,0.030161,-0.008119,0.016644,0.036673,-0.000619,0.041895,0.032947,-0.011643
2019-01-07,0.003832,0.003453,0.009664,0.017342,0.000089,0.011835,0.007854,-0.002952
2019-01-08,0.006464,-0.002712,0.006470,0.015215,0.002207,0.009005,0.009351,-0.002632
...,...,...,...,...,...,...,...,...
2024-12-23,0.006503,-0.004720,-0.002676,-0.002301,-0.002902,0.009695,0.005970,-0.009215
2024-12-24,0.003566,0.001990,0.003185,0.008903,0.003089,0.013469,0.011054,0.004220
2024-12-26,0.004734,0.006728,0.002541,0.010199,0.000934,-0.000680,0.000067,-0.000569
2024-12-27,-0.001444,-0.006894,-0.003431,-0.014685,-0.004210,-0.013382,-0.010582,-0.008232
2024-12-30,-0.006591,-0.003195,0.001399,-0.007719,0.004304,-0.013389,-0.011477,0.008005

In [17]:
prices

,EFA,GLD,HYG,IWM,LQD,QQQ,SPY,TLT
Date,,,,,,,,
2007-04-11,44.219479,67.080002,32.021992,62.195061,50.453194,37.935265,101.382843,48.607006
2007-04-12,44.514740,66.989998,32.043472,62.613289,50.529099,38.235615,101.833389,48.618099
2007-04-13,44.662357,67.839996,31.985174,63.016041,50.443672,38.312836,102.297989,48.467922
2007-04-16,45.133625,68.400002,31.972891,63.883572,50.486397,38.664623,103.269440,48.734982
2007-04-17,45.139305,68.000000,31.957541,63.689892,50.761600,38.750446,103.544014,49.007565
...,...,...,...,...,...,...,...,...
2024-12-23,72.980751,240.960007,72.909065,218.558975,100.825233,519.576416,586.186646,82.844894
2024-12-24,73.241432,241.440002,73.141632,220.513489,101.137184,526.621826,592.702087,83.195229
2024-12-26,73.589012,243.070007,73.327713,222.773987,101.231682,526.264038,592.741577,83.147881
2024-12-27,73.482803,241.399994,73.076523,219.526352,100.806343,519.268372,586.502014,82.466179
2024-12-30,73.000069,240.630005,73.178833,217.838364,101.241142,512.362183,579.809143,83.128937